# Generated by Django 3.2.7 on 2021-10-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incognito', '0002_setting_table_ap_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_table',
            name='mask1',
            field=models.CharField(blank=True, max_length=1, verbose_name='mask1'),
        ),
        migrations.AddField(
            model_name='setting_table',
            name='mask2',
            field=models.CharField(blank=True, max_length=1, verbose_name='mask2'),
        ),
        migrations.AddField(
            model_name='setting_table',
            name='route_gateway1',
            field=models.CharField(blank=True, max_length=15, verbose_name='gateway N°1'),
        ),
        migrations.AddField(
            model_name='setting_table',
            name='route_gateway2',
            field=models.CharField(blank=True, max_length=15, verbose_name='gateway N°2'),
        ),
        migrations.AddField(
            model_name='setting_table',
            name='route_reach1',
            field=models.CharField(blank=True, max_length=15, verbose_name='host N°1'),
        ),
        migrations.AddField(
            model_name='setting_table',
            name='route_reach2',
            field=models.CharField(blank=True, max_length=15, verbose_name='host N°2'),
        ),
    ]
