# Generated by Django 3.2.7 on 2021-11-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incognito', '0004_auto_20211029_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_table',
            name='mask1',
            field=models.CharField(blank=True, max_length=2, verbose_name='mask1'),
        ),
        migrations.AlterField(
            model_name='setting_table',
            name='mask2',
            field=models.CharField(blank=True, max_length=2, verbose_name='mask2'),
        ),
    ]
