# Generated by Django 3.2.7 on 2021-11-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incognito', '0005_auto_20211105_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_table',
            name='received_datas',
            field=models.CharField(blank=True, max_length=10, verbose_name='received_datas'),
        ),
        migrations.AlterField(
            model_name='monitoring_table',
            name='sent_datas',
            field=models.CharField(blank=True, max_length=10, verbose_name='sent_datas'),
        ),
        migrations.AlterField(
            model_name='monitoring_table',
            name='space_free',
            field=models.CharField(blank=True, max_length=10, verbose_name='free space'),
        ),
        migrations.AlterField(
            model_name='monitoring_table',
            name='space_total',
            field=models.CharField(blank=True, max_length=10, verbose_name='total space'),
        ),
    ]
