# Generated by Django 3.2.7 on 2021-12-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incognito', '0006_auto_20211117_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring_table',
            name='in_datas',
            field=models.CharField(blank=True, max_length=11, verbose_name='incoming_datas'),
        ),
        migrations.AddField(
            model_name='monitoring_table',
            name='out_datas',
            field=models.CharField(blank=True, max_length=11, verbose_name='outcoming_datas'),
        ),
    ]
